# (c) 2025 Copyright, Real-Time Innovations, Inc. All rights reserved.
# No duplications, whole or partial, manual or electronic, may be made
# without express written permission.  Any such copies, or revisions thereof,
# must display this notice unaltered.
# This code contains trade secrets of Real-Time Innovations, Inc.

# Ubuntu 22.04 is supported by RTI Connext DDS 7.3.0
# Use Docker's multi-stage build capability to create an image that
# contains only Ubuntu and the fully-installed RTI Connext distribution
#
# this image uses the rticom/routing-service:7.3.0 located in Docker hub


FROM rticom/routing-service:7.3.0

WORKDIR /config

ENV NDDSHOME=/opt/rti.com/rti_connext_dds-7.3.0
# Set up the DDS execution environment
ENV PATH=$NDDSHOME/bin:$NDDSHOME/resource/app/bin/x64Linux4gcc7.3.0/:/app/build:$PATH
ENV LD_LIBRARY_PATH=$NDDSHOME/lib/x64Linux4gcc7.3.0

COPY RSConfig.xml RSConfig.xml
COPY Window.xml Window.xml
